-- Creacion de tablas
DROP TABLE IF EXISTS ROL;
CREATE TABLE ROL
(   IdRol SERIAL NOT NULL,
    NombreRol TEXT NOT NULL,
    PRIMARY KEY(IdRol));

DROP TABLE IF EXISTS USUARIO;
CREATE TABLE USUARIO
(   IdUsuario SERIAL NOT NULL,
    NombreUsuario TEXT,
    Correo TEXT NOT NULL,
    Contraseña TEXT NOT NULL,
    IdRol INT,
    PRIMARY KEY(IdUsuario),
    FOREIGN KEY(IdRol) REFERENCES ROL(IdRol));

DROP TABLE IF EXISTS PERMISO;
CREATE TABLE PERMISO
(   IdPermiso SERIAL NOT NULL,
    NombrePermiso TEXT NOT NULL,
    DescripcionPermiso TEXT,
    PRIMARY KEY(IdPermiso));

DROP TABLE IF EXISTS ROL_PERMISO;
CREATE TABLE ROL_PERMISO
(   IdRolPermiso SERIAL NOT NULL,
    IdRol INT,
    IdPermiso INT,
    PRIMARY KEY(IdRolPermiso),
    FOREIGN KEY(IdRol) REFERENCES ROL(IdRol),
    FOREIGN KEY(IdPermiso) REFERENCES PERMISO(IdPermiso));

DROP TABLE IF EXISTS UBICACION;
CREATE TABLE UBICACION
(   IdUbicacion SERIAL NOT NULL,
    Region TEXT NOT NULL,
    Comuna TEXT,
    Calle TEXT,
    Numero INT,
    IdUsuario INT,
    PRIMARY KEY(IdUbicacion),
    FOREIGN KEY(IdUsuario) REFERENCES USUARIO(IdUsuario));

DROP TABLE IF EXISTS LISTA_DESEOS;
CREATE TABLE LISTA_DESEOS
(   IdListaDeseos SERIAL NOT NULL,
    IdUsuario INT,
    PRIMARY KEY(IdListaDeseos),
    FOREIGN KEY(IdUsuario) REFERENCES USUARIO(IdUsuario));

DROP TABLE IF EXISTS PRODUCTO;
CREATE TABLE PRODUCTO
(   IdProducto SERIAL NOT NULL,
    NombreProducto TEXT,
    DescripcionProducto TEXT,
    TipoProducto TEXT,
    Stock INT,
    Precio INT,
    UrlProducto TEXT,
    PRIMARY KEY(IdProducto));

DROP TABLE IF EXISTS LISTA_DESEOS_PRODUCTO;
CREATE TABLE LISTA_DESEOS_PRODUCTO
(   IdListaProducto SERIAL NOT NULL,
    IdListaDeseos INT,
    IdProducto INT,
    PRIMARY KEY(IdListaProducto), 
    FOREIGN KEY(IdListaDeseos) REFERENCES LISTA_DESEOS(IdListaDeseos),
    FOREIGN KEY(IdProducto) REFERENCES PRODUCTO(IdProducto));

DROP TABLE IF EXISTS CATEGORIA_PRODUCTO;
CREATE TABLE CATEGORIA_PRODUCTO
(   IdCategoriaProducto SERIAL NOT NULL,
    NombreCategoriaProducto TEXT NOT NULL,
    DescripcionCategoriaProducto TEXT,
    PRIMARY KEY(IdCategoriaProducto));

DROP TABLE IF EXISTS PRODUCTO_CATEGORIAPRODUCTO;
CREATE TABLE PRODUCTO_CATEGORIAPRODUCTO
(   IdProducto_Categoria SERIAL NOT NULL,
    IdProducto INT,
    IdCategoriaProducto INT,
    PRIMARY KEY (IdProducto_Categoria),
    FOREIGN KEY (IdProducto) REFERENCES PRODUCTO(IdProducto),
    FOREIGN KEY (IdCategoriaProducto) REFERENCES CATEGORIA_PRODUCTO(IdCategoriaProducto));

DROP TABLE IF EXISTS CARRO_DE_COMPRAS;
CREATE TABLE CARRO_DE_COMPRAS
(   IdCarro SERIAL NOT NULL,
    IdUsuario INT,
    PRIMARY KEY (IdCarro),
    FOREIGN KEY (IdUsuario) REFERENCES USUARIO(IdUsuario));
    
DROP TABLE IF EXISTS PRODUCTO_CARRODECOMPRAS;
CREATE TABLE PRODUCTO_CARRODECOMPRAS
(   IdProducto_Carro SERIAL NOT NULL,
    IdProducto INT,
    IdCarro INT,
    PRIMARY KEY (IdProducto_Carro),
    FOREIGN KEY (IdProducto) REFERENCES PRODUCTO(IdProducto),
    FOREIGN KEY (IdCarro) REFERENCES CARRO_DE_COMPRAS(IdCarro));

DROP TABLE IF EXISTS MEDIO_DE_PAGO;
CREATE TABLE MEDIO_DE_PAGO
(   IdMedioPago SERIAL,
    NombreMedioPago TEXT,
    DescripcionMedioPago TEXT,
    PRIMARY KEY (IdMedioPago));

DROP TABLE IF EXISTS BOLETA_DE_COMPRA;
CREATE TABLE BOLETA_DE_COMPRA
(   IdBoleta SERIAL,
    FechaBoleta DATE,
    MontoBoleta INT,
    IdCarro INT,
    IdMedioPago INT,
    PRIMARY KEY (IdBoleta),
    FOREIGN KEY (IdCarro) REFERENCES CARRO_DE_COMPRAS (IdCarro),
    FOREIGN KEY (IdMedioPago) REFERENCES MEDIO_DE_PAGO (IdMedioPago));

DROP TABLE IF EXISTS USUARIO_PUBLICA_PRODUCTO;
CREATE TABLE USUARIO_PUBLICA_PRODUCTO
(   IdPublicado SERIAL,
    IdProducto INT,
    IdUsuario INT,
    PRIMARY KEY (IdPublicado),
    FOREIGN KEY (IdProducto) REFERENCES PRODUCTO (IdProducto),
    FOREIGN KEY (IdUsuario) REFERENCES USUARIO (IdUsuario));

DROP TABLE IF EXISTS USUARIO_VALORA_PRODUCTO;
CREATE TABLE USUARIO_VALORA_PRODUCTO
(   IdValorado SERIAL NOT NULL,
    IdUsuario INT,
    IdProducto INT,
    Valoracion INT,
    CHECK (Valoracion BETWEEN 1 AND 10),
    PRIMARY KEY(IdValorado),
    FOREIGN KEY(IdUsuario) REFERENCES USUARIO(IdUsuario),
    FOREIGN KEY(IdProducto) REFERENCES PRODUCTO(IdProducto));